# Generated by Django 3.1.4 on 2021-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('year', models.IntegerField(max_length=10)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
    ]
