# Generated by Django 3.1.4 on 2021-01-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='year',
            field=models.IntegerField(),
        ),
    ]
