# Generated by Django 3.1.4 on 2021-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20210102_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=100)),
                ('reg_event', models.CharField(max_length=200)),
            ],
        ),
    ]
