# Generated by Django 3.1.4 on 2021-01-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participants',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reg_event',
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(choices=[('CS', 'CS'), ('EC', 'EC'), ('EEE', 'EEE'), ('EBE', 'EBE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=35),
        ),
    ]
