# Generated by Django 3.1.4 on 2021-01-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_registration_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
    ]
